service: serverless-jsdom-layer

custom:
    region: ap-northeast-1
    serverless-layers:
        layersDeploymentBucket: serverless-jsdom-layer-deploy

provider:
    name: aws
    runtime: nodejs10.x
    region: ${self:custom.region}
    timeout: 60
    memorySize: 128

package:
    exclude:
        - package.json
        - package-log.json

functions:
    jsdom-test:
        handler: myhandler.handler

plugins:
    - serverless-layers
